# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 781)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.texte_shell = QtWidgets.QTextEdit(self.centralwidget)
        self.texte_shell.setGeometry(QtCore.QRect(20, 410, 581, 311))
        self.texte_shell.setStyleSheet("color: rgb(0, 243, 28);\n"
"font: 9pt \"Microsoft JhengHei UI\";\n"
"background-color: rgb(3, 3, 3);")
        self.texte_shell.setObjectName("texte_shell")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 581, 161))
        self.groupBox.setObjectName("groupBox")
        self.tbx_user = QtWidgets.QTextBrowser(self.groupBox)
        self.tbx_user.setGeometry(QtCore.QRect(10, 20, 451, 131))
        self.tbx_user.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";")
        self.tbx_user.setObjectName("tbx_user")
        self.btn_user_logout = QtWidgets.QPushButton(self.groupBox)
        self.btn_user_logout.setGeometry(QtCore.QRect(470, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_user_logout.setFont(font)
        self.btn_user_logout.setObjectName("btn_user_logout")
        self.btn_user_signin = QtWidgets.QPushButton(self.groupBox)
        self.btn_user_signin.setGeometry(QtCore.QRect(470, 110, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_user_signin.setFont(font)
        self.btn_user_signin.setObjectName("btn_user_signin")
        self.lined_user_new_name = QtWidgets.QLineEdit(self.groupBox)
        self.lined_user_new_name.setGeometry(QtCore.QRect(470, 70, 101, 31))
        self.lined_user_new_name.setObjectName("lined_user_new_name")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 190, 581, 181))
        self.groupBox_2.setMouseTracking(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.cb_activ_ps = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_activ_ps.setGeometry(QtCore.QRect(20, 40, 201, 20))
        self.cb_activ_ps.setTabletTracking(True)
        self.cb_activ_ps.setChecked(False)
        self.cb_activ_ps.setObjectName("cb_activ_ps")
        self.cb_activ_nfc = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_activ_nfc.setGeometry(QtCore.QRect(20, 90, 201, 20))
        self.cb_activ_nfc.setTabletTracking(True)
        self.cb_activ_nfc.setChecked(False)
        self.cb_activ_nfc.setObjectName("cb_activ_nfc")
        self.cb_activ_base_cont = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_activ_base_cont.setGeometry(QtCore.QRect(20, 140, 201, 20))
        self.cb_activ_base_cont.setTabletTracking(True)
        self.cb_activ_base_cont.setChecked(False)
        self.cb_activ_base_cont.setObjectName("cb_activ_base_cont")
        self.btn_save_product = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_save_product.setGeometry(QtCore.QRect(250, 110, 291, 51))
        self.btn_save_product.setObjectName("btn_save_product")
        self.tbx_stock_state = QtWidgets.QTextBrowser(self.groupBox_2)
        self.tbx_stock_state.setGeometry(QtCore.QRect(250, 40, 181, 51))
        self.tbx_stock_state.setObjectName("tbx_stock_state")
        self.btn_flip_stock_state = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_flip_stock_state.setGeometry(QtCore.QRect(450, 40, 93, 51))
        self.btn_flip_stock_state.setObjectName("btn_flip_stock_state")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(610, 20, 451, 551))
        self.groupBox_3.setObjectName("groupBox_3")
        self.tbx_product = QtWidgets.QTextBrowser(self.groupBox_3)
        self.tbx_product.setGeometry(QtCore.QRect(10, 20, 431, 521))
        self.tbx_product.setObjectName("tbx_product")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(610, 570, 451, 151))
        self.groupBox_4.setObjectName("groupBox_4")
        self.btn_search = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_search.setGeometry(QtCore.QRect(320, 20, 121, 31))
        self.btn_search.setObjectName("btn_search")
        self.lined_search = QtWidgets.QLineEdit(self.groupBox_4)
        self.lined_search.setGeometry(QtCore.QRect(50, 20, 251, 31))
        self.lined_search.setObjectName("lined_search")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.label.setObjectName("label")
        self.tbx_search = QtWidgets.QTextBrowser(self.groupBox_4)
        self.tbx_search.setGeometry(QtCore.QRect(10, 60, 431, 81))
        self.tbx_search.setObjectName("tbx_search")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.texte_shell.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft JhengHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\">&gt;&gt; </span></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "User ID"))
        self.tbx_user.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:36pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_user_logout.setText(_translate("MainWindow", "User Log out"))
        self.btn_user_signin.setText(_translate("MainWindow", "User Sign in"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Control Panel"))
        self.cb_activ_ps.setText(_translate("MainWindow", "Activate Product Scanning"))
        self.cb_activ_nfc.setText(_translate("MainWindow", "Activate NFC Scanning"))
        self.cb_activ_base_cont.setText(_translate("MainWindow", "Activate Base Connection"))
        self.btn_save_product.setText(_translate("MainWindow", "Save Product to DataBase"))
        self.tbx_stock_state.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In Stock</p></body></html>"))
        self.btn_flip_stock_state.setText(_translate("MainWindow", "Flip State"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Product scaned"))
        self.groupBox_4.setTitle(_translate("MainWindow", "GroupBox"))
        self.btn_search.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "ID："))
