# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_setting(object):
    def setupUi(self, Dialog_setting):
        Dialog_setting.setObjectName("Dialog_setting")
        Dialog_setting.resize(400, 375)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_setting)
        self.buttonBox.setGeometry(QtCore.QRect(40, 300, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.cb_base_portal = QtWidgets.QComboBox(Dialog_setting)
        self.cb_base_portal.setGeometry(QtCore.QRect(90, 80, 221, 31))
        self.cb_base_portal.setObjectName("cb_base_portal")
        self.cb_barcode_portal = QtWidgets.QComboBox(Dialog_setting)
        self.cb_barcode_portal.setGeometry(QtCore.QRect(90, 210, 221, 31))
        self.cb_barcode_portal.setObjectName("cb_barcode_portal")
        self.label = QtWidgets.QLabel(Dialog_setting)
        self.label.setGeometry(QtCore.QRect(40, 40, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_setting)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog_setting)
        self.buttonBox.accepted.connect(Dialog_setting.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_setting.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_setting)

    def retranslateUi(self, Dialog_setting):
        _translate = QtCore.QCoreApplication.translate
        Dialog_setting.setWindowTitle(_translate("Dialog_setting", "COM Setting"))
        self.label.setText(_translate("Dialog_setting", "Base Node Portal"))
        self.label_2.setText(_translate("Dialog_setting", "Barcode Scanner Portal"))
